# Generated by Django 5.0.6 on 2026-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BD', 'Business Developer'), ('ANALYST', 'Analyst'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='BD', max_length=20),
        ),
    ]
