# Generated by Django 5.0.6 on 2026-06-26 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0004_deal_stage2_decision_deal_stage2_rationale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('SENT', 'Sent to client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('executive_summary', models.TextField(blank=True)),
                ('scope_of_work', models.TextField(blank=True)),
                ('proposed_tariff_ngn_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_tenor_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_contract_value_usd_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('commercial_terms', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('validity_until', models.DateField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposal', to='deals.deal')),
            ],
            options={
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalStateHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_history', to='proposals.proposal')),
            ],
            options={
                'verbose_name_plural': 'proposal state history',
                'db_table': 'proposal_state_history',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField()),
                ('content', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='proposals.proposal')),
            ],
            options={
                'db_table': 'proposal_documents',
                'ordering': ['-version'],
                'unique_together': {('proposal', 'version')},
            },
        ),
    ]
