# Generated by Django 5.0.6 on 2026-06-28 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0005_dealcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('project_life_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('debt_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('debt_tenor_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('discount_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_cost_models', to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cost_model', to='deals.deal')),
            ],
            options={
                'db_table': 'cost_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CAPEX', 'Capital (one-off)'), ('OPEX', 'Operating (annual)')], max_length=5)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cost_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='costing.costmodel')),
            ],
            options={
                'db_table': 'cost_lines',
                'ordering': ['kind', 'order', 'id'],
            },
        ),
    ]
