# Generated by Django 5.0.6 on 2026-06-24 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('pass_condition', models.TextField()),
                ('required_evidence', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'knockout_gates',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('weight_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pass_threshold', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pillars',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('weight_in_pillar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('band_1_def', models.TextField(blank=True, help_text='Score 1 — Very Poor')),
                ('band_3_def', models.TextField(blank=True, help_text='Score 3 — Moderate')),
                ('band_5_def', models.TextField(blank=True, help_text='Score 5 — Excellent')),
                ('method_evidence', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria', to='screening.pillar')),
            ],
            options={
                'db_table': 'sub_criteria',
                'ordering': ['pillar__code', 'order', 'id'],
            },
        ),
    ]
