# Generated by Django 5.0.6 on 2026-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriterion',
            name='higher_is_better',
            field=models.BooleanField(default=True, help_text='For numeric sub-criteria: does a larger figure score higher?'),
        ),
        migrations.AddField(
            model_name='subcriterion',
            name='input_type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric (auto-scored from a figure)'), ('QUALITATIVE', 'Qualitative (band selected from evidence)')], default='QUALITATIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='subcriterion',
            name='numeric_bands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subcriterion',
            name='unit',
            field=models.CharField(blank=True, help_text="Unit shown next to a numeric input, e.g. '%', 'years', 'months'.", max_length=24),
        ),
    ]
