# Generated by Django 5.0.6 on 2026-06-24 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_ref', models.CharField(editable=False, max_length=32, unique=True)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REJECTED_TO_BD', 'Rejected to BD'), ('STAGE1_PASSED', 'Stage 1 passed'), ('DECLINED', 'Declined')], default='DRAFT', max_length=20)),
                ('current_rejection_reason', models.TextField(blank=True)),
                ('stage1_decision', models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('DECLINED', 'Declined')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=255)),
                ('deal_type', models.CharField(blank=True, choices=[('GREENFIELD', 'Greenfield'), ('BROWNFIELD', 'Brownfield'), ('JV', 'JV')], max_length=20)),
                ('sub_sector', models.CharField(blank=True, max_length=64)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('counterparty_class', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('sponsor', models.CharField(blank=True, max_length=255)),
                ('sponsor_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deal_source', models.CharField(blank=True, max_length=64)),
                ('total_project_cost_usd_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('installed_capacity', models.CharField(blank=True, max_length=64)),
                ('proposed_tariff_ngn_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenor_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('revenue_2_3yr_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('capital_structure', models.CharField(blank=True, max_length=64)),
                ('ebitda_usd_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('leverage_usd_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_position_usd_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='deals.deal')),
            ],
            options={
                'db_table': 'deal_intake',
            },
        ),
        migrations.CreateModel(
            name='EditAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_access_requests', to='deals.deal')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edit_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edit_access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealGateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('PASS', 'Pass'), ('CONDITIONAL', 'Conditional'), ('FAIL', 'Fail')], max_length=12)),
                ('evidence_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_results', to='deals.deal')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening.knockoutgate')),
            ],
            options={
                'db_table': 'deal_gate_results',
                'ordering': ['gate__number'],
                'unique_together': {('deal', 'gate')},
            },
        ),
        migrations.CreateModel(
            name='DealPillarComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pillar_comments', to='deals.deal')),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening.pillar')),
            ],
            options={
                'db_table': 'deal_pillar_comments',
                'ordering': ['pillar__code'],
                'unique_together': {('deal', 'pillar')},
            },
        ),
    ]
