# Generated by Django 5.0.6 on 2026-06-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage1_decision',
            field=models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('CONDITIONAL', 'Passed (conditional)'), ('DECLINED', 'Declined')], max_length=12),
        ),
    ]
