# Generated by Django 5.0.6 on 2026-06-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_stage1_decision'),
        ('screening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSubCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1 — Very Poor'), (3, '3 — Moderate'), (5, '5 — Excellent')])),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_scores', to='deals.deal')),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sub_criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screening.subcriterion')),
            ],
            options={
                'db_table': 'deal_sub_criterion_scores',
                'ordering': ['sub_criterion__pillar__code', 'sub_criterion__order'],
                'unique_together': {('deal', 'sub_criterion')},
            },
        ),
    ]
