# Generated by Django 5.0.6 on 2026-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_dealsubcriterionscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='stage2_decision',
            field=models.CharField(blank=True, choices=[('GO', 'GO'), ('CONDITIONAL', 'Conditional GO'), ('NO_GO', 'NO-GO')], max_length=12),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage2_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REJECTED_TO_BD', 'Rejected to BD'), ('STAGE1_PASSED', 'Stage 1 passed'), ('DECLINED', 'Declined'), ('STAGE2_GO', 'Stage 2 — GO'), ('STAGE2_CONDITIONAL', 'Stage 2 — Conditional GO'), ('STAGE2_NO_GO', 'Stage 2 — NO-GO')], default='DRAFT', max_length=20),
        ),
    ]
