# Generated by Django 5.0.6 on 2026-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_dealcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsubcriterionscore',
            name='measured_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REJECTED_TO_BD', 'Rejected to BD'), ('STAGE1_PASSED', 'Stage 1 passed'), ('AWAITING_IC_REVIEW', 'Awaiting Management Investment Committee Review'), ('DECLINED', 'Declined'), ('STAGE2_GO', 'Stage 2 — GO'), ('STAGE2_CONDITIONAL', 'Stage 2 — Conditional GO'), ('STAGE2_NO_GO', 'Stage 2 — NO-GO')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealsubcriterionscore',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 — Very Poor'), (2, '2 — Poor'), (3, '3 — Moderate'), (4, '4 — Good'), (5, '5 — Excellent')]),
        ),
    ]
