# Generated by Django 5.0.6 on 2026-07-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('deals', '0006_dealsubcriterionscore_measured_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='classification',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('NURTURE', 'Nurture (parked)'), ('DEFERRED', 'Deferred (external blocker)')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='classification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='approval_process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='competition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='current_supply',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='current_tariff_ngn_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='decision_maker',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='key_risks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='load_profile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='metering_data_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='monthly_energy_spend_ngn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='sales_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='agents.salesagent'),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='site_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dealintake',
            name='win_probability_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
