# Generated by Django 5.0.6 on 2026-06-24 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealFieldHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=128)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_history', to='deals.deal')),
            ],
            options={
                'verbose_name': 'deal field history entry',
                'verbose_name_plural': 'deal field history',
                'db_table': 'deal_field_history',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DealStateHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_state', models.CharField(blank=True, max_length=32)),
                ('to_state', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_history', to='deals.deal')),
            ],
            options={
                'verbose_name': 'deal state history entry',
                'verbose_name_plural': 'deal state history',
                'db_table': 'deal_state_history',
                'ordering': ['occurred_at', 'id'],
            },
        ),
    ]
