# Generated by Django 5.0.6 on 2026-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('DEAL_SUBMITTED', 'Deal submitted'), ('DEAL_UNDER_REVIEW', 'Deal taken for review'), ('DEAL_RETURNED', 'Deal returned to BD'), ('STAGE1_DECISION', 'Stage 1 decision'), ('EDIT_REQUESTED', 'Edit access requested'), ('EDIT_DECISION', 'Edit access decision')], max_length=32),
        ),
    ]
