# Generated by Django 5.0.6 on 2026-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('DEAL_SUBMITTED', 'Deal submitted'), ('DEAL_UNDER_REVIEW', 'Deal taken for review'), ('DEAL_RETURNED', 'Deal returned to BD'), ('STAGE1_DECISION', 'Stage 1 decision'), ('STAGE2_DECISION', 'Stage 2 decision'), ('EDIT_REQUESTED', 'Edit access requested'), ('EDIT_DECISION', 'Edit access decision'), ('PROPOSAL_UPDATE', 'Proposal update'), ('PROJECT_UPDATE', 'Project update')], max_length=32),
        ),
    ]
